# -*- coding: utf-8 -*-
# DCS F-16C Early Access Guide EN, p.43-79 (Cockpit Overview) 기반 패널 정의
SRC = "DCS F-16C Early Access Guide EN"

def C(cid, grid, name, type_, positions, no=None, push=None, note=""):
    return dict(cid=cid, grid=grid, name=name, type=type_, positions=positions, no=no or "", push=push, note=note)

def LIGHT(cid, grid, name, meaning, no=None, note=""):
    return C(cid, grid, name, "Indicator light", [("OFF", "소등"), ("ON", meaning)], no, note=note)

def BTN(cid, grid, name, action, no=None, note=""):
    return C(cid, grid, name, "Push button (momentary)", [("PUSH", action)], no, push="PUSH: " + action, note=note)

def IND(cid, grid, name, reading, no=None, note=""):
    return C(cid, grid, name, "Indicator (gauge/readout)", [("NA", reading)], no, note=note)

def P(code, tab, panel, location, pages, rows, cols, controls, note=""):
    return dict(code=code, tab=tab, panel=panel, location=location, source=f"{SRC}, p.{pages}",
                rows=rows, cols=cols, controls=controls, note=note)

NI = "DCS N/I (미구현)"

DCS_PANELS = [

# ───────────── Instrument Panel ─────────────
P("AOAIDX", "AOA IDX", "AOA INDEXER", "Instrument Panel (HUD 좌측)", "44", 4, 1, [
    C("DIM", (1,1), "Dimming Lever", "Lever (continuous)", [("ADJ", "아래로 돌리면 인덱서 등 밝기 감소")], 1),
    LIGHT("HIGH", (2,1), "High AoA Indicator Light", "AoA 14° 이상 — 에너지 손실, 최적보다 큰 AoA", 2),
    LIGHT("OPT", (3,1), "Optimal AoA Indicator Light", "AoA 11.1°~13.9° — on-speed", 3),
    LIGHT("LOW", (4,1), "Low AoA Indicator Light", "AoA 11° 이하 — 에너지 증가, 최적보다 작은 AoA", 4),
], note="착륙 시 AoA 11~13° 유지. 기어 위치와 무관하게 항상 작동"),

P("ARNWS", "AR-NWS", "AR STATUS / NWS INDICATOR", "Instrument Panel (HUD 우측)", "45", 4, 1, [
    C("DIM", (1,1), "Dimming Lever", "Lever (continuous)", [("ADJ", "아래로 돌리면 표시등 밝기 감소")], 1),
    LIGHT("RDY", (2,1), "RDY Indicator Light", "공중급유 도어 개방 및 준비 완료", 2),
    LIGHT("AR_NWS", (3,1), "AR/NWS Indicator Light", "공중: 급유 붐 결합(latched). 지상: NWS 활성, 러더 페달로 조향", 3),
    LIGHT("DISC", (4,1), "DISC Indicator Light", "급유 붐 분리됨. 3초 후 자동으로 RDY로 복귀", 4),
]),

P("LEYEBROW", "L EYEBROW", "LEFT EYEBROW LIGHTS", "Instrument Panel (좌측 상단)", "45", 3, 2, [
    C("MASTER_CAUTION", (1,2), "MASTER CAUTION Button/Light", "Push button light",
      [("OFF", "소등"), ("ON", "Caution Light Panel에 고장/특정 조건 발생"), ("PUSH", "리셋(소등)")], 1,
      push="PUSH: MASTER CAUTION 리셋"),
    LIGHT("TF_FAIL", (2,2), "TF-FAIL Warning Light", "TF(지형추적) 고장 — Block 50 비기능", 2, note="Block 50 비기능"),
    BTN("F_ACK", (2,1), "F-ACK Button", "PFLD 고장 메시지 확인(acknowledge) 및 종류/심각도에 따라 PFLD에서 삭제", 3),
    BTN("IFF_IDENT", (3,1), "IFF IDENT Button", "트랜스폰더 identification-of-position 수행 (비암호 질문 응답 시 자기 위치 순간 강조)", 4),
]),

P("REYEBROW", "R EYEBROW", "RIGHT EYEBROW WARNING LIGHTS", "Instrument Panel (우측 상단)", "46-47", 1, 8, [
    LIGHT("ENG_FIRE", (1,1), "ENG FIRE Warning Light", "엔진실 화재 감지", 1),
    LIGHT("ENGINE", (1,2), "ENGINE Warning Light", "RPM <60% 또는 FTIT >1,100°C 2초 이상 (과열/화염소실/정체)", 2),
    LIGHT("HYD_OIL_PRESS", (1,3), "HYD/OIL PRESS Warning Light", "엔진 오일압 <10 PSI 30초 이상(>20 PSI 시 소등) 또는 유압계통 A/B <1,000 PSI", 3),
    LIGHT("FLCS", (1,4), "FLCS Warning Light", "FLCS 프로세서/전원/입력/센서 고장, FLCS BIT 실패, 또는 LEF 잠김", 4),
    LIGHT("DBU_ON", (1,5), "DBU ON Warning Light", "FLCS가 Digital Backup 모드로 자동 전환되거나 FLT CONTROL 패널로 수동 선택됨", 5),
    LIGHT("TO_LDG_CONFIG", (1,6), "TO/LDG CONFIG Warning Light", "고도 <10,000 ft + 속도 <190 kt + 강하율 >250 fpm(또는 WOW) + 기어 미고정/TEF 미전개 → 기어 경고음 동반", 6),
    LIGHT("CANOPY", (1,7), "CANOPY Warning Light", "캐노피 미하강/미잠금", 7),
    LIGHT("OXY_LOW", (1,8), "OXY LOW Warning Light", "BOS 고갈 및 <5 PSI. OBOGS BIT 시작 시 10초 점등, 고장 시 유지", 8),
]),

P("MISC", "MISC", "MISCELLANEOUS (MISC) PANEL", "Instrument Panel (좌측 하단)", "47-48", 7, 2, [
    C("RF", (1,1), "RF Switch", "3-position toggle switch",
      [("NORM", "모든 전자파 방사 허용"),
       ("QUIET", "FCR 추적모드/ACM만, AIFF 질문, TNDL 저출력, ECM MAN/SEMI 수동 활성 시, 레이더고도계로 제한 (TACAN 수신 전용)"),
       ("SILENT", "FCR ACM만, AIFF 질문, ECM MAN/SEMI 수동 활성 시로 제한. TNDL/TACAN 수신 전용, CARA 금지")], 1,
      note="Run silent 스위치. 시스템별 영향 표: p.48"),
    LIGHT("ECM", (2,1), "ECM Enable Light", "ECM 포드가 재밍 신호 방사 중 (장착·전원 시)", 2),
    C("LASER_ARM", (3,1), "LASER ARM Switch", "2-position toggle switch",
      [("LASER_ARM", "타게팅 포드 레이저 조사 허용 (포드 미차폐 시)"), ("OFF", "레이저 조사 금지")], 3),
    BTN("ALT_REL", (4,1), "ALT REL Button", "SSC 무장 투하 버튼 고장 시 백업 투하", 4),
    C("MASTER_ARM", (5,1), "MASTER ARM Switch", "3-position toggle switch",
      [("MASTER_ARM", "FCR/SMS 무장 운용 큐 및 심볼 제공, 투하/비상투하 허용"),
       ("OFF", "무장 투하 금지, 비상투하 허용"),
       ("SIMULATE", "큐/심볼 제공하나 투하 금지, 비상투하 허용")], 5),
    BTN("ADV_MODE", (6,1), "ADV MODE Button", "지형추적 레이더 Advanced Mode — Block 50 미사용", 6, note="Block 50 미사용"),
    C("AP_ROLL", (7,1), "Autopilot ROLL Switch", "3-position toggle switch",
      [("HDG_SEL", "선택 방위 유지"), ("ATT_HOLD", "롤 자세 유지"), ("STRG_SEL", "스티어포인트 조향")], 7,
      note="Autopilot 절 참조"),
    C("AP_PITCH", (7,2), "Autopilot PITCH Switch", "3-position toggle switch",
      [("ALT_HOLD", "고도 유지"), ("AP_OFF", "오토파일럿 OFF (중립)"), ("ATT_HOLD", "피치 자세 유지")], 7),
]),

P("INSTR", "INSTR", "INSTRUMENT PANEL GAUGES (SAI/ASI/ALT/ADI/AOA/VVI/FUEL FLOW/ENGINE)", "Instrument Panel (중앙·우측)", "49-53", 4, 5, [
    C("ASI_SET_INDEX", (1,1), "Airspeed/Mach Indicator — SET INDEX Knob", "Rotary knob (continuous)",
      [("ADJ", "속도 기준 지표(Airspeed Reference Index) 위치 조정")], 6, note="ASI: 80~850 kt 외측 눈금, Mach 0.5~2.2 창, VNE 800 kt"),
    C("ADI_PITCH_TRIM", (1,2), "ADI — Pitch Trim Knob", "Rotary knob (continuous, ±0.5°/click)",
      [("ADJ", "항공기 심볼 대비 자세구의 상대 피치 조정 (화살표가 흰 점에 정렬 시 0)")], 13,
      note="ADI: INS 자세, ILS 시 로컬라이저/글라이드슬로프 표시. OFF 플래그=INS 자세 미수신, AUX 플래그=INS 저하"),
    C("ALT_BARO", (1,3), "Altimeter — Barometric Setting Knob", "Rotary knob (continuous)",
      [("ADJ", "Kollsman 창 기압 보정값(inHg) 설정 — QNH 사용")], 6, note="-1,000~80,000 ft, 100 ft 단위"),
    C("ALT_MODE", (1,4), "Altimeter — Mode Switch", "2-position momentary toggle switch",
      [("ELEC", "CADC 전기식 모드 (주)"), ("PNEU", "피토정압 공압식 모드 (보조). CADC/서보 고장 시 자동 전환, PNEU 플래그 표시")], 7),
    C("SAI_CAGE", (1,5), "Standby Attitude Indicator — PULL TO CAGE Knob", "Pull/rotate knob",
      [("IN", "정상 — 회전 시 피치 트림 조정 (±25°, 5° 눈금)"),
       ("PULLED", "케이지 — 자세구 수평 고정, OFF 플래그 표시"),
       ("PULLED_CCW", "케이지 상태로 잠금")], 6,
      note="SAI는 기수 4° 상향 장착. 적극 기동 후 오차 가능 — 수평비행·피치 +4°에서 케이지"),
    IND("AOA_IND", (2,1), "Angle-of-Attack Indicator", "-5°~+32° 테이프. 고(14~16.5°)/최적(11.1~13.9°)/저(8.5~11°) 영역 마커", None),
    IND("VVI", (2,3), "Vertical Velocity Indicator", "±6,000 fpm 테이프 (500 fpm 주눈금, 100 fpm 보조눈금)", None),
    IND("FUEL_FLOW", (2,4), "Fuel Flow Indicator", "연료 소모율 PPH, 100 lb 단위", None),
    IND("OIL_PRESS", (2,5), "Engine OIL Pressure Indicator", "0~100 PSI. 지상 아이들 15 PSI, 공중 MIL 이상 60 PSI 정상", 1),
    IND("NOZ_POS", (3,5), "Engine NOZ POS Indicator", "노즐 개방율 % (20% 주눈금, 10% 보조눈금)", 2),
    IND("RPM", (4,5), "Engine RPM Indicator", "0~110% (0~60% 5% 단위, 65% 이상 1% 단위)", 3),
    IND("FTIT", (4,4), "Engine FTIT Indicator", "200~1,200°C 팬 터빈 입구 온도", 4),
], note="HUD/ICP/DED/MFD/EHSI/RWR는 별도 장 — 본 범위(p.43-79) 외"),

P("FUELQTY", "FUEL QTY SEL", "FUEL QTY SEL PANEL", "Instrument Panel (우측 하단)", "54", 2, 1, [
    C("QTY_SEL", (1,1), "FUEL QTY SEL Knob", "6-position rotary knob",
      [("TEST", "AL/FR 바늘 2,000 lb, 토탈라이저 6,000 lb 표시, FWD/AFT FUEL LOW 점등"),
       ("NORM", "AL=후방 저장조+A-1 동체탱크, FR=전방 저장조+F-1/F-2 동체탱크 합. Bingo 계산 활성"),
       ("RSVR", "AL=후방 저장조, FR=전방 저장조 잔량"),
       ("INT_WING", "AL=좌 내부 날개탱크, FR=우 내부 날개탱크"),
       ("EXT_WING", "AL=좌 외부 날개탱크, FR=우 외부 날개탱크"),
       ("EXT_CTR", "FR=외부 중앙탱크, AL=0")], 1),
    C("EXT_FUEL_TRANS", (2,1), "EXT FUEL TRANS Switch", "2-position toggle switch",
      [("NORM", "외부 중앙탱크 → 외부 날개탱크 순 이송"), ("WING_FIRST", "외부 날개탱크 → 외부 중앙탱크 순 이송")], 2),
]),

# ───────────── Left Auxiliary Console ─────────────
P("LG", "LG PANEL", "LANDING GEAR PANEL", "Left Auxiliary Console", "55-57", 4, 4, [
    BTN("EMER_STORES_JETT", (1,1), "EMER STORES JETTISON Button", "1초 누르면 SMS 전원 인가 후 외부 연료탱크·랙·자유낙하 무장(스테이션 3~7) 비상투하. AAM 미투하. 지상(WOW)에서는 GND JETT ENABLE 필요", 1),
    C("HOOK", (1,3), "HOOK Switch", "2-position toggle switch",
      [("UP", "훅 공압 해제 — 활주로 와이어 위로 들어 올려 택시 가능 (완전 수납 불가)"), ("DN", "훅 수납 위치에서 해제, 공압으로 완전 전개")], 2),
    C("WHEELS_LIGHTS", (1,4), "WHEELS Down Lights (NOSE / LEFT / RIGHT)", "3 x indicator light",
      [("OFF", "소등"), ("ON", "녹색 — 해당 기어 다운 & 잠김")], 3),
    C("GND_JETT_ENABLE", (2,1), "GND JETT ENABLE Switch", "2-position toggle switch",
      [("ENABLE", "기어/WOW 무관하게 모든 무장 투하 조건 허용 (정비용)"),
       ("OFF", "기어 다운+WOW 시 비상투하·선택투하·정상투하 금지. 기어 다운 시 선택/정상투하 금지")], 5),
    C("BRAKES_CHAN", (2,2), "BRAKES Channel Switch", "2-position toggle switch",
      [("CHAN_1", "토 브레이크 채널 1 (정상)"), ("CHAN_2", "토 브레이크 채널 2")], 6),
    C("ANTI_SKID", (2,3), "ANTI-SKID / PARKING BRAKE Switch", "3-position toggle switch",
      [("PARKING_BRAKE", "WOW+스로틀 OFF/IDLE 시 주기어에 풀 브레이크. 스로틀 IDLE+1인치 전진 시 ANTI-SKID로 자동 복귀"),
       ("ANTI_SKID", "토 브레이크 85% 미만: 감속 스키드 제어, 85% 이상: 최대 성능 스키드 제어"),
       ("OFF", "안티스키드·파킹 브레이크 비활성")], 7),
    C("LG_HANDLE", (2,4), "LG Handle", "2-position handle",
      [("UP", "기어 접기 명령"), ("DN", "기어 내림 명령")], 4,
      note="핸들 내 경고등: 기어/도어 이동 중 또는 잠금 실패 시 점등 (TO/LDG CONFIG 시에도 점등)"),
    C("STORES_CONFIG", (3,1), "STORES CONFIG Switch", "2-position toggle switch",
      [("CAT_I", "외부 날개탱크 없는 공대공 무장, 또는 외부 날개탱크+AAM 6발(중앙탱크·AIM-120 없음)"),
       ("CAT_III", "공대지 무장, 외부 날개탱크+중앙탱크, 또는 AIM-120 포함 AAM 6발+외부 날개탱크 — FLCS AoA/롤 제한")], 9,
      note="잘못 설정 시 STORES CONFIG caution 점등. 이착륙 구성(기어 다운/급유도어 개방) 시 무효"),
    BTN("HORN_SILENCER", (3,2), "HORN SILENCER Button", "기어 경고음·저속 경고음 소거", 10),
    C("LIGHTS", (3,3), "LANDING / TAXI LIGHTS Switch", "3-position toggle switch",
      [("LANDING", "착륙등 ON"), ("OFF", "착륙등·택시등 OFF"), ("TAXI", "택시등 ON")], 11,
      note="LG 핸들 UP 시 자동 소등"),
    BTN("DN_LOCK_REL", (3,4), "DN LOCK REL Button", "LG 핸들 잠금 솔레노이드 수동 해제. WOW 신호 무시하고 지상에서 기어 접기 허용", 8),
    C("SPD_BRK_IND", (4,1), "SPEED BRAKE Position Indicator", "Indicator (3-state)",
      [("CLOSED", "스피드브레이크 완전 수납"), ("OPEN", "9점 패턴 — 어떤 각도든 전개"), ("NO_POWER", "줄무늬 — 전원 없음")], 12),
]),

P("HMCS", "HMCS", "HMCS CONTROL PANEL", "Left Auxiliary Console", "57", 1, 1, [
    C("SYMBOLOGY_INT", (1,1), "SYMBOLOGY INT Knob", "Rotary knob (power + brightness)",
      [("OFF", "헬멧 바이저 HMCS 심볼 제거"), ("INC_ON", "CW 회전 시 HMCS 심볼 밝기 증가")], 1),
]),

P("ALTGEAR", "ALT GEAR", "ALT GEAR HANDLE", "Left Auxiliary Console (하단)", "57", 1, 1, [
    C("ALT_GEAR", (1,1), "ALT GEAR Handle", "Pull handle",
      [("STOWED", "정상"), ("PULLED", "유압 고장 또는 주 LG 핸들 사용 불가 시 기어 비상 전개")], 1),
]),

# ───────────── Right Auxiliary Console ─────────────
P("RAUXINST", "R AUX INSTR", "RIGHT AUX CONSOLE INSTRUMENTS", "Right Auxiliary Console", "58-61", 3, 3, [
    IND("MAG_COMPASS", (1,1), "Magnetic Compass", "자북 기준 기수 방위 (자립형, 주전원/항법 고장 시 참조용. 정밀 항법 부적합)", None),
    IND("FUEL_QTY", (1,2), "Fuel Quantity Indicator", "토탈라이저 숫자(lb) + AL/FR 바늘 (100 lb 단위). 바늘 괴리 시 빨간 표시 → ENG FEED 노브로 보정. 참조 탱크는 FUEL QTY SEL 노브로 선택", None),
    IND("HYD_PRESS", (1,3), "HYD PRESS A & B Indicators", "유압계통 A/B 압력 0~4,000 PSI (500 PSI 단위). 정상 2,850~3,250 PSI", None),
    IND("PFLD", (2,1), "Pilot Fault List Display (PFLD)", "FLCS 감지 고장 목록. WARNING(괄호 표시)/CAUTION 2종. F-ACK로 삭제", None),
    IND("EPU_FUEL", (2,3), "EPU Fuel Quantity Indicator", "하이드라진 잔량 % (5% 단위). 100% ≈ 10~15분 운용", None),
    IND("CABIN_PRESS", (3,2), "Cabin Pressure Indicator", "객실 압력고도 0~50,000 ft (1,000 ft 단위)", None),
    C("CLOCK_KNOB", (3,3), "Mechanical Clock — Wind/Control Knob", "Rotary/pull knob",
      [("ROTATE_CW", "시계 태엽 감기"), ("PULLED_ROTATE", "당긴 상태로 회전 시 시각 조정")], 4,
      note="8일 기계식 시계. 임무 시작 시 현지 시각으로 자동 설정"),
]),

P("CAUTION", "CAUTION LTS", "CAUTION LIGHT PANEL", "Right Auxiliary Console", "59-60", 8, 4, [
    LIGHT("FLCS_FAULT", (1,1), "FLCS FAULT", "FLCC 이중 고장, LEF 잠김, 또는 FLCS BIT 실패"),
    LIGHT("ENGINE_FAULT", (1,2), "ENGINE FAULT", "엔진 관련 고장 감지 (확인 시 소등)"),
    LIGHT("AVIONICS_FAULT", (1,3), "AVIONICS FAULT", "항전 고장 또는 MUX 버스가 엔진/FLCC와 통신 상실"),
    LIGHT("SEAT_NOT_ARMED", (1,4), "SEAT NOT ARMED", "사출좌석 arming 레버가 dis-armed(UP) 위치"),
    LIGHT("ELEC_SYS", (2,1), "ELEC SYS", "전기 고장 — ELEC 패널 관련 표시등 점등"),
    LIGHT("SEC", (2,2), "SEC", "엔진 Secondary 제어 모드 운용 중"),
    LIGHT("EQUIP_HOT", (2,3), "EQUIP HOT", "항전 베이 냉각 공기 온도/압력 부족 — FCR 전원 자동 차단"),
    LIGHT("NWS_FAIL", (2,4), "NWS FAIL", "노즈휠 조향 계통 고장"),
    LIGHT("PROBE_HEAT", (3,1), "PROBE HEAT", "피토/동체 공기자료/AoA 프로브 공기흐름 감소(결빙 가능) 또는 프로브 히터/감시계통 고장"),
    LIGHT("FUEL_OIL_HOT", (3,2), "FUEL/OIL HOT", "엔진 공급 연료 또는 엔진 오일 과열"),
    LIGHT("RADAR_ALT", (3,3), "RADAR ALT", "레이더 고도계 고장"),
    LIGHT("ANTI_SKID", (3,4), "ANTI SKID", "ANTI-SKID 스위치 OFF 또는 지상속도 >5 kt에서 제동계통 고장"),
    LIGHT("CADC", (4,1), "CADC", "중앙 공기자료 컴퓨터 고장"),
    LIGHT("INLET_ICING", (4,2), "INLET ICING", "엔진 흡입구 결빙 감지 또는 감지기 고장"),
    LIGHT("IFF", (4,3), "IFF", "Mode 4 질문 수신했으나 응답 불가 (RF 스위치/MODE 4 REPLY 스위치로 금지, 또는 Mode 4 제로화)"),
    LIGHT("HOOK", (4,4), "HOOK", "비상 어레스팅 훅이 수납·잠금 상태 아님"),
    LIGHT("STORES_CONFIG", (5,1), "STORES CONFIG", "STORES CONFIG 스위치 위치 부적절"),
    LIGHT("OVERHEAT", (5,2), "OVERHEAT", "엔진실/주기어 휠웰/ECS 베이/EPU 베이 과열"),
    LIGHT("NUCLEAR", (5,3), "NUCLEAR", "미구현", note=NI),
    LIGHT("OBOGS", (5,4), "OBOGS", "ECS 공기 압력 <10 PSI"),
    LIGHT("ATF_NOT_ENGAGED", (6,1), "ATF NOT ENGAGED", "기능 없음", note="No function"),
    LIGHT("EEC", (6,2), "EEC", "기능 없음", note="No function"),
    LIGHT("BLANK_6_3", (6,3), "(blank)", "—"),
    LIGHT("CABIN_PRESS", (6,4), "CABIN PRESS", "객실 압력고도 >27,000 ft"),
    LIGHT("FWD_FUEL_LOW", (7,1), "FWD FUEL LOW", "전방 저장조 연료 <400 lb"),
    LIGHT("BUC", (7,2), "BUC", "기능 없음", note="No function"),
    LIGHT("BLANK_7_3", (7,3), "(blank)", "—"),
    LIGHT("BLANK_7_4", (7,4), "(blank)", "—"),
    LIGHT("AFT_FUEL_LOW", (8,1), "AFT FUEL LOW", "후방 저장조 연료 <250 lb"),
    LIGHT("BLANK_8_2", (8,2), "(blank)", "—"),
    LIGHT("BLANK_8_3", (8,3), "(blank)", "—"),
    LIGHT("BLANK_8_4", (8,4), "(blank)", "—"),
], note="8행×4열 그림 순서 그대로. PFLD 항목 표시 시 대응 caution 등 + MASTER CAUTION 점등"),

# ───────────── Left Console ─────────────
P("MPO", "MPO", "MANUAL PITCH OVERRIDE SWITCH", "Left Console (후방)", "62", 1, 1, [
    C("MPO", (1,1), "MANUAL PITCH Override Switch", "2-position toggle switch (spring-loaded to NORM)",
      [("NORM", "정상 (스프링 복귀 위치)"),
       ("OVRD", "유지하는 동안 수평안정판 권한 증가 — 딥스톨 회복용. SSC 롤/요 입력 금지, 러더 페달 요 입력은 유지")], 1),
]),

P("ENGJET", "ENG & JET START", "ENG & JET START CONTROL PANEL", "Left Console", "63", 4, 2, [
    LIGHT("JFS_RUN", (1,1), "JET FUEL — RUN Light", "JFS 시동 후 30초 내 정격 속도 도달", 1),
    C("JFS", (1,2), "JET FUEL — JFS Switch", "3-position toggle switch",
      [("START_1", "브레이크/JFS 축압기 1개로 JFS 기동"),
       ("OFF", "JFS 정지. 지상 시동 시 RPM 55%에서 자동 OFF, 공중 재시동 시 수동 OFF 필요"),
       ("START_2", "축압기 2개로 JFS 기동 — 외기 >38°C 또는 <-7°C, 또는 20,000 ft 미만 재시동 시 필요")], 2,
      note="FUEL 패널 MASTER OFF여도 JFS 기동 가능"),
    C("ENG_CONT", (2,2), "ENG CONT Switch", "2-position guarded toggle switch",
      [("PRI", "Primary — DEC(디지털 엔진 제어)로 정상 운용"),
       ("SEC", "Secondary — MEC 유압기계식 연료 스케줄. SEC caution 점등. AB 불가, 노즐 폐쇄 고정, 아이들 추력 증가")], 3),
    C("AB_RESET", (3,2), "AB RESET Switch", "3-position toggle switch (spring-loaded to NORM)",
      [("AB_RESET", "F110-GE-129 장착기 비기능"), ("NORM", "정상"),
       ("ENG_DATA", "순간 위치 — 전후 6초/2초 포함 8초 엔진 데이터를 EMSC에 기록")], 4, note=NI),
    C("MAX_POWER", (4,2), "MAX POWER Switch", "2-position guarded toggle switch",
      [("MAX_POWER", "F110-GE-129 장착기 비기능"), ("OFF", "정상")], 5, note="비기능"),
]),

P("EPU", "EPU", "EPU CONTROL PANEL", "Left Console", "64", 2, 3, [
    C("EPU", (1,1), "EPU Switch", "3-position guarded toggle switch",
      [("OFF", "지상: EPU 수동 OFF. 공중: 주/대기 발전기 모두 고장 아니면 EPU OFF. 이륙 후 계속 OFF였으면 공중 EPU 작동 금지"),
       ("NORM", "정상 — 이륙 후 주/대기 발전기 전력 상실 또는 유압 A/B 모두 고장 시 자동 작동. 지상 엔진 정지 시 자동 작동 안 함"),
       ("ON", "EPU 수동 ON")], 1),
    LIGHT("RUN", (1,2), "EPU Run Light", "EPU 작동 중, EPU 유압펌프 토출압 >2,000 PSI", 2),
    LIGHT("AIR", (1,3), "AIR Light", "EPU가 엔진 블리드 에어로 작동 중", 3),
    LIGHT("HYDRAZN", (2,3), "HYDRAZN Light", "EPU가 하이드라진으로 작동 중 (RPM 82~90% 미만 또는 엔진 완전 고장 시)", 4),
], note="블리드 에어/하이드라진 비상 유압·전력 10~15분 공급. 엔진 고장 시 유압 A + 전기계통에 전력"),

P("ELEC", "ELEC", "ELEC CONTROL PANEL", "Left Console", "64-65", 6, 3, [
    C("MAIN_PWR", (1,1), "MAIN PWR Switch", "3-position toggle switch",
      [("MAIN_PWR", "주 발전기 또는 외부전원을 전기계통에 연결, 대기 발전기 활성. AC 없으면 배터리 버스만 배터리 공급"),
       ("BATT", "주 발전기·외부전원 분리 및 주 발전기 리셋, 대기 발전기 분리. 배터리 버스만 배터리 공급"),
       ("OFF", "공중: 주 발전기 분리, 대기 발전기 비활성. 지상: 주 발전기·외부전원 분리, 대기 발전기 비활성")], 1),
    LIGHT("FLCS_PMG", (1,3), "FLCS PMG Light", "공중: FLCS 모든 브랜치가 PMG 전력 미수신. 지상: WOW 60초 후 1개 이상 브랜치 PMG 미수신", 3),
    LIGHT("MAIN_GEN", (2,3), "MAIN GEN Light", "비필수 AC 버스에 외부전원/주 발전기 전력 없음", 4),
    BTN("CAUTION_RESET", (3,1), "ELEC CAUTION RESET Button", "MASTER CAUTION·ELEC SYS caution 소등, 주/대기 발전기 리셋", 2),
    LIGHT("STBY_GEN", (3,3), "STBY GEN Light", "대기 발전기 전력 사용 불가", 5),
    LIGHT("EPU_GEN", (4,3), "EPU GEN Light", "EPU ON 명령됐으나 양쪽 비상 버스에 전력 미공급 (EPU OFF+WOW+엔진 구동 시 금지)", 6),
    LIGHT("EPU_PMG", (5,3), "EPU PMG Light", "EPU ON 명령됐으나 EPU PMG가 FLCS 전 브랜치에 전력 미공급", 7),
    LIGHT("TO_FLCS", (6,1), "ACFT BATT — TO FLCS Light", "공중: 1개 이상 FLCS 브랜치가 배터리 버스 ≤25 V 수신. 지상: 배터리가 FLCS 브랜치에 공급 중", 9),
    LIGHT("FLCS_RLY", (6,2), "ACFT BATT — FLCS RLY Light", "FLCS 브랜치가 배터리 버스 <20 V 수신 또는 배터리 버스 미연결. FLT CONTROL 패널 FLCS RESET으로 리셋", 10),
    LIGHT("FAIL", (6,3), "ACFT BATT — FAIL Light", "공중: 배터리 고장(≤20 V). 지상: WOW 60초 후 배터리/충전기 고장", 8),
]),

P("AVTR", "AVTR", "AVTR CONTROL PANEL", "Left Console", "66", 1, 3, [
    C("VIDEO_SELECT", (1,1), "VIDEO SELECT Knob", "Rotary knob",
      [("HUD", "HUD 및 MFD 녹화"), ("HMD", "HMCS 및 MFD 녹화")], None, note=NI + " — 각인 기준"),
    BTN("EVENT_MARK", (1,2), "EVENT MARK Button", "이벤트 마크 기록", None, note=NI + " — 각인 기준"),
    C("RECORD", (1,3), "RECORD / UNTHRD Switch", "2-position toggle switch",
      [("RECORD", "녹화"), ("UNTHRD", "Unthread (테이프 해제)")], None, note=NI + " — 각인 기준"),
], note="Airborne Video Tape Recorder — " + NI),

P("FUEL", "FUEL", "FUEL CONTROL PANEL", "Left Console", "67", 1, 4, [
    C("MASTER", (1,1), "FUEL MASTER Switch", "2-position guarded toggle switch",
      [("MASTER", "엔진 주 연료 차단 밸브 개방 (정상, 가드 닫힘)"), ("OFF", "주 연료 차단 밸브 폐쇄")], 1),
    C("TANK_INERTING", (1,2), "TANK INERTING Switch", "2-position toggle switch",
      [("TANK_INERTING", "할론 가스를 연료탱크에 주입 — 내부압 감소·화재 위험 감소 (비상/피탄 시)"), ("OFF", "정상")], 2),
    C("ENG_FEED", (1,3), "ENGINE FEED Knob", "4-position rotary knob",
      [("OFF", "부스트 펌프 모두 OFF — FFP(유압 A 구동)로 연료 공급"),
       ("NORM", "부스트 펌프 모두 ON — 전후방 탱크에서 공급, CG 자동 유지"),
       ("AFT", "후방 펌프만 — 후방 탱크 공급, 후방 연료가 전방으로 이송, CG 전방 이동"),
       ("FWD", "전방 펌프만 — 전방 탱크 공급, 전방 연료가 후방으로 이송, CG 후방 이동")], 3),
    C("AIR_REFUEL", (1,4), "AIR REFUEL Switch", "2-position toggle switch",
      [("OPEN", "급유 도어 개방, 내부탱크 감압·외부탱크 감압, 동체/수직미익 AR 투광등 활성. <400 kt 시 FLCS 이착륙 게인"),
       ("CLOSE", "급유 도어 폐쇄, 재가압, AR 투광등 소등")], 4),
]),

P("EXTLT", "EXT LIGHTING", "EXT LIGHTING CONTROL PANEL", "Left Console", "69-70", 2, 4, [
    C("ANTI_COLL", (1,1), "ANTI-COLL Knob", "8-position rotary knob",
      [("OFF", "충돌방지등 OFF"), ("1", "점멸 패턴 1"), ("2", "점멸 패턴 2"), ("3", "점멸 패턴 3"), ("4", "점멸 패턴 4"),
       ("A", "점멸 패턴 A"), ("B", "점멸 패턴 B"), ("C", "점멸 패턴 C")], 4, note="패턴 그림 p.69"),
    C("FLASH_STEADY", (1,2), "POSITION — FLASH/STEADY Switch", "2-position toggle switch",
      [("FLASH", "WING/TAIL 위치등 점멸"), ("STEADY", "WING/TAIL 위치등 고정")], 1),
    C("WING_TAIL", (1,3), "POSITION — WING/TAIL Switch", "3-position toggle switch",
      [("BRT", "날개끝 적/녹 + 미익 백색 위치등 밝게"), ("OFF", "날개끝 등은 FORM 노브 밝기로 복귀"), ("DIM", "위치등 어둡게")], 2),
    C("FUSELAGE", (1,4), "FUSELAGE Switch", "3-position toggle switch",
      [("BRT", "수직미익 조명 동체등 밝게"), ("OFF", "OFF"), ("DIM", "어둡게")], 3),
    C("FORM", (2,1), "FORM Knob", "Rotary knob (OFF→BRT)",
      [("OFF", "편대등 OFF"), ("INC_BRT", "날개끝 적/녹 + 중앙동체 상하 백색 편대등 밝기 증가 (WING/TAIL=OFF 시 날개끝 등에 적용)")], 5),
    C("MASTER", (2,2), "MASTER Knob", "5-position rotary knob",
      [("OFF", "모든 외부등 OFF"),
       ("COVERT_ALL", "AERIAL REFUELING만 노브 적용(AR REFUEL OPEN 필요), 나머지 OFF"),
       ("COVERT_A_C", "ANTI-COLL OFF, WING/TAIL·FUSELAGE 스위치 적용, FORM 노브 적용(WING/TAIL OFF 필요), AR 노브 적용"),
       ("COVERT_FORM", "ANTI-COLL 스위치 적용, WING/TAIL·FUSELAGE·FORM OFF, AR 노브 적용"),
       ("ALL", "모든 스위치/노브 설정 적용")], 7, note="조합표 p.70"),
    C("AERIAL_REFUELING", (2,4), "AERIAL REFUELING Knob", "Rotary knob (OFF→BRT)",
      [("OFF", "급유구 조명 OFF"), ("INC_BRT", "동체 급유구 조명 밝기 증가 (FUEL 패널 AR REFUEL=OPEN 시만)")], 6),
]),

P("FLTCTL", "FLT CONTROL", "FLT CONTROL PANEL", "Left Console", "71", 3, 3, [
    C("DIGITAL_BACKUP", (1,1), "DIGITAL BACKUP Switch", "2-position toggle switch",
      [("BACKUP", "FLCC 백업 소프트웨어 선택 — DBU ON 경고등 + HUD WARN 점멸"), ("OFF", "정상")], 1),
    C("MANUAL_TF_FLYUP", (1,2), "MANUAL TF FLY-UP Switch", "2-position toggle switch",
      [("ENABLE", "지형추적 fly-up 활성 — Block 50 미사용"), ("DISABLE", "비활성")], 2, note="Block 50 미사용"),
    C("ALT_FLAPS", (1,3), "ALT FLAPS Switch", "2-position toggle switch",
      [("EXTEND", "TEF 수동 전개 (착륙 전 저속, TEF 자동 전개 실패 시)"), ("NORM", "FLCS 명령에 따른 TEF 자동 스케줄")], 3),
    C("RUN_FAIL", (2,3), "FLCS RUN / FAIL Indicator Lights", "2 x indicator light",
      [("RUN", "녹색 — FLCS BIT 진행 중 (완료 시 소등)"), ("FAIL", "적색 — BIT 중 문제 발견, PFLD에 고장 표시")], 4),
    C("LE_FLAPS", (3,1), "LE FLAPS Switch", "2-position toggle switch",
      [("LOCK", "LEF 현 위치 잠금, FLCS 경고등 점등 (비대칭 플랩 고장 시)"), ("AUTO", "FLCS 명령에 따른 LEF 자동 스케줄")], 5, note=NI),
    C("FLCS_RESET", (3,2), "FLCS RESET Switch", "2-position momentary toggle switch",
      [("RESET", "FLCS 경고등·서보/전기 고장 리셋. FLCS/MASTER CAUTION/CADC/FLCS caution 리셋, PFLD 삭제"), ("OFF", "정상")], 6),
    C("FLCS_BIT", (3,3), "FLCS BIT Switch", "2-position toggle switch (magnetically held)",
      [("BIT", "WOW + 지상속도 <28 kt 시 FLCS BIT 시작 (약 45초, 완료 시 OFF로 자동 복귀)"), ("OFF", "정상")], 7),
]),

P("TRIM", "MANUAL TRIM", "MANUAL TRIM PANEL", "Left Console", "72", 2, 2, [
    C("ROLL_TRIM", (1,1), "ROLL TRIM Wheel & Indicator", "Trim wheel (continuous)",
      [("ADJ", "롤 축 수동 트림, 적용량 표시 (L WING DN / R WING DN)")], 1),
    C("TRIM_AP_DISC", (1,2), "TRIM/AP DISC Switch", "2-position toggle switch",
      [("NORM", "SSC 4-way 트림 스위치 또는 본 패널로 피치/롤 트림, 오토파일럿 허용"),
       ("DISC", "본 패널로만 트림, SSC 트림 스위치 비활성, 오토파일럿 금지")], 4),
    C("YAW_TRIM", (2,1), "YAW TRIM Knob", "Rotary knob (continuous)",
      [("ADJ", "요 축 수동 트림, 외측 점 패턴으로 적용량 표시")], 2),
    C("PITCH_TRIM", (2,2), "PITCH TRIM Wheel & Indicator", "Trim wheel (continuous)",
      [("ADJ", "피치 축 수동 트림, 적용량 표시 (NOSE UP / NOSE DN)")], 3),
], note="SSC 트림 스위치 고장 시 사용. 정상 시 FLCS 자동 트림"),

P("TEST", "TEST", "TEST PANEL", "Left Console", "72-73", 3, 3, [
    BTN("FIRE_OHEAT", (1,1), "FIRE & OHEAT DETECT Test Button", "화재/과열 감지 회로 연속성 시험 — ENG FIRE 경고등·OVERHEAT caution·MASTER CAUTION 점등", 1),
    C("OBOGS_BIT", (1,2), "OBOGS BIT Switch", "2-position momentary toggle switch",
      [("BIT", "OBOGS 시험 — OXY LOW 10초 점등, 고장 시 유지"), ("OFF", "정상")], 2),
    BTN("MAL_IND_LTS", (1,3), "MAL & IND LTS Test Button", "모든 경고/주의/표시등 및 음성 메시지 점검", 3),
    C("PROBE_HEAT", (2,1), "PROBE HEAT Switch", "3-position toggle switch",
      [("HEAT", "지상에서 피토/공기자료/AoA/온도 프로브 가열 + 감시계통 활성"),
       ("OFF", "지상에서 프로브 가열 OFF"),
       ("TEST", "프로브 히트 감시 시험 — 성공 시 PROBE HEAT caution 점멸")], 4, note="공중에서는 항상 자동 가열"),
    C("EPU_GEN_TEST", (2,2), "EPU/GEN Test Switch", "2-position momentary toggle switch",
      [("TEST", "하이드라진 없이 EPU 발전기·PMG 출력을 FLCS 채널에 시험 (지상)"), ("OFF", "정상")], 5),
    C("FLCS_PWR_LIGHTS", (2,3), "FLCS PWR Lights (A/B/C/D)", "4 x indicator light",
      [("OFF", "소등"), ("ON", "FLCS PWR TEST=TEST 시 각 채널(A,B,C,D) 전력 출력 표시")], 6),
    C("FLCS_PWR_TEST", (3,3), "FLCS PWR TEST Switch", "3-position toggle switch",
      [("TEST", "FLCS 채널 전력 출력 시험 (MAIN PWR=BATT 또는 MAIN PWR)"),
       ("NORM", "정상 (EPU/GEN=TEST + MAIN PWR 시 EPU PMG 가용성 시험)"),
       ("MAINT", "지상 정비 시험용")], 7),
]),

P("CANOPY", "CANOPY", "CANOPY SWITCH / LEVER / JETTISON / DEFOG", "Left Console (전방)", "73-74", 2, 2, [
    C("SWITCH", (1,1), "Canopy Switch", "3-position toggle switch (spring-loaded to center from DOWN)",
      [("UP", "캐노피 레버 UNLOCKED 시 캐노피 완전 개방 (완료 시 자동 중립 복귀)"),
       ("CENTER", "액추에이터 정지"),
       ("DOWN", "유지하는 동안 캐노피 하강 (완전 폐쇄까지 유지 필요)")], 1),
    C("LEVER", (1,2), "Canopy Lever", "2-position lever",
      [("UNLOCKED", "밖으로 당김 — 압력 씰 감압, CANOPY 경고등 점등. 하강 전 이 위치 필요. 스로틀 레버 행정 물리적 제한"),
       ("LOCKED", "벽쪽으로 올림 — 캐노피 잠금, 씰 가압")], 2),
    C("JETTISON", (2,1), "CANOPY JETTISON T-Handle", "Pull handle",
      [("STOWED", "정상"), ("PULLED", "캐노피 비상 분리 (사출 핸들 당겼으나 캐노피 미분리 시)")], None),
    C("DEFOG", (2,2), "DEFOG Lever", "Lever (continuous MIN↔MAX)",
      [("MIN", "공기 대부분을 좌석 뒤 벤트로"), ("MAX", "공기 대부분을 전방 캐노피·계기판 하단 벤트로. TEMP=AUTO 시 3분간 최대 온풍")], None),
]),

# ───────────── Right Console ─────────────
P("SNSRPWR", "SNSR PWR", "SNSR PWR CONTROL PANEL", "Right Console", "75", 1, 4, [
    C("LEFT_HDPT", (1,1), "LEFT HDPT Switch", "2-position toggle switch",
      [("ON", "좌측 chin 하드포인트 센서(AN/ASQ-213 HTS) 전원"), ("OFF", "OFF")], 1),
    C("RIGHT_HDPT", (1,2), "RIGHT HDPT Switch", "2-position toggle switch",
      [("ON", "우측 chin 하드포인트 센서(AN/AAQ-33 타게팅 포드) 전원"), ("OFF", "OFF")], 2),
    C("FCR", (1,3), "FCR Switch", "2-position toggle switch",
      [("FCR", "AN/APG-68 레이더 전원"), ("OFF", "OFF")], 3),
    C("RDR_ALT", (1,4), "RDR ALT Switch", "3-position toggle switch",
      [("RDR_ALT", "레이더 고도계 송신"), ("STBY", "전원 ON, 송신 안 함"), ("OFF", "전원 OFF")], 4),
]),

P("INTLT", "INT LIGHTING", "INTERIOR LIGHTING CONTROL PANEL", "Right Console", "76", 2, 3, [
    C("PRI_CONSOLES", (1,1), "PRIMARY — CONSOLES Knob", "Rotary knob (OFF→BRT)",
      [("OFF", "OFF"), ("INC_BRT", "좌측 보조콘솔·좌/우 콘솔 패널 백라이트 밝기 증가")], 1),
    C("PRI_INST_PNL", (1,2), "PRIMARY — INST PNL Knob", "Rotary knob (OFF→BRT)",
      [("OFF", "OFF (완전 CCW 시 MAL&IND LTS 자동 BRT)"), ("INC_BRT", "계기판·우측 보조콘솔 패널 백라이트 밝기 증가")], 2),
    C("PRI_DED", (1,3), "PRIMARY — DATA ENTRY DISPLAY Knob", "Rotary knob (OFF→BRT)",
      [("OFF", "OFF"), ("INC_BRT", "DED·PFLD 밝기 증가")], 3),
    C("FLOOD_CONSOLES", (2,1), "FLOOD — CONSOLES Knob", "Rotary knob (OFF→HIGH INT)",
      [("OFF", "OFF"), ("INC", "좌측 보조콘솔·좌/우 콘솔 플러드 조명 증가"), ("HIGH_INT", "HIGH INT 디텐트 초과 시 MAL&IND LTS 자동 BRT")], 4),
    C("FLOOD_INST_PNL", (2,2), "FLOOD — INST PNL Knob", "Rotary knob (OFF→BRT)",
      [("OFF", "OFF"), ("INC_BRT", "계기판·우측 보조콘솔 플러드 조명 증가")], 5),
    C("MAL_IND_LTS", (2,3), "MAL & IND LTS Switch", "2-position toggle switch",
      [("BRT", "고장/표시등·CMDS 카운터 밝게"), ("DIM", "어둡게")], 6),
]),

P("AIRCOND", "AIR COND", "AIR COND CONTROL PANEL", "Right Console", "76", 1, 2, [
    C("TEMP", (1,1), "TEMP Knob", "Rotary knob (COOL↔WARM, AUTO detent)",
      [("COOL", "냉방"), ("AUTO", "자동"), ("WARM", "난방")], 1, note=NI),
    C("AIR_SOURCE", (1,2), "AIR SOURCE Knob", "4-position rotary knob",
      [("OFF", "엔진 블리드 밸브 모두 폐쇄 — 공조·냉각·여압(G-suit, 여압호흡, OBOGS, 캐노피 씰, 연료탱크 가압) 모두 정지"),
       ("NORM", "ECS·여압 자동"),
       ("DUMP", "객실 감압, 조절된 블리드 에어로 객실·항전 환기"),
       ("RAM", "객실 감압 + 블리드 밸브 폐쇄, 외부 램 공기로 환기 — 여압 기능 모두 정지")], 2,
      note="OFF/RAM 시 외부탱크 연료 이송 불가"),
]),

P("KY58", "KY-58", "KY-58 SECURE VOICE PANEL", "Right Console", "77", 1, 4, [
    C("MODE", (1,1), "KY-58 MODE Knob", "Rotary knob",
      [("P", "Plain"), ("C", "Cipher"), ("LD", "Load"), ("RV", "Receive Variable")], None, note=NI + " — 실제 KY-58 각인 기준"),
    C("FILL", (1,2), "KY-58 FILL Knob", "Rotary knob",
      [("Z", "Zeroize"), ("1", "키 1"), ("2", "키 2"), ("3", "키 3"), ("4", "키 4"), ("5", "키 5"), ("6", "키 6")], None, note=NI + " — 실제 KY-58 각인 기준"),
    C("POWER", (1,3), "KY-58 POWER Switch", "3-position toggle switch",
      [("OFF", "OFF"), ("ON", "ON"), ("TD", "Time Delay")], None, note=NI + " — 실제 KY-58 각인 기준"),
    C("VOLUME", (1,4), "KY-58 VOLUME Knob", "Rotary knob (continuous)",
      [("ADJ", "볼륨")], None, note=NI),
], note="보안 음성 암호화 — " + NI),

P("PLAINCIPHER", "PLAIN-CIPHER", "PLAIN/CIPHER SWITCH", "Right Console", "77", 1, 1, [
    C("PLAIN_CIPHER", (1,1), "PLAIN/CIPHER Switch", "3-position toggle switch",
      [("CRAD_1", "암호 무선 1"), ("PLAIN", "평문"), ("CRAD_2", "암호 무선 2")], None, note=NI + " — 각인 기준"),
]),

P("OXYGEN", "OXYGEN", "OXYGEN REGULATOR PANEL", "Right Console", "77", 2, 3, [
    IND("FLOW", (1,1), "OXYGEN REGULATOR FLOW Indicator", "백/흑 교대 — 백색=산소 흐름 있음, 흑색=없음", 1),
    IND("SUPPLY_PRESS", (1,2), "OXYGEN SUPPLY Indicator", "산소 압력, 정상 10~55 PSI", 2),
    C("EMERGENCY", (2,1), "EMERGENCY Lever", "3-position lever",
      [("EMERGENCY", "양압으로 최대 산소 — 누설 시험용"), ("NORMAL", "객실 압력고도 >28,000 ft 시 양압"), ("TEST_MASK", "양압 최대 산소 — 지원요원 누설 시험용")], 3, note=NI),
    C("DILUTER", (2,2), "Diluter Lever", "2-position lever",
      [("100_PCT", "순산소 최대 공급"), ("NORM", "객실 압력고도에 따른 객실 공기/산소 혼합")], 4, note=NI),
    C("SUPPLY", (2,3), "SUPPLY Lever", "3-position lever",
      [("PBG", "마스크 산소 공급 + G 기반 여압호흡(>4G) 가능"), ("ON", "마스크 산소 공급, 여압호흡 없음"), ("OFF", "마스크 산소 공급 차단")], 5),
]),

P("AVPWR", "AVIONICS PWR", "AVIONICS POWER CONTROL PANEL", "Right Console", "78-79", 2, 5, [
    C("MMC", (1,1), "MMC Switch", "2-position toggle switch", [("MMC", "Modular Mission Computer 전원"), ("OFF", "OFF")], 1),
    C("ST_STA", (1,2), "ST STA Switch", "2-position toggle switch", [("ST_STA", "날개 하부·동체 중앙 스테이션 전원"), ("OFF", "OFF")], 2),
    C("MFD", (1,3), "MFD Switch", "2-position toggle switch", [("MFD", "MFD 2대 전원"), ("OFF", "OFF")], 3),
    C("UFC", (1,4), "UFC Switch", "2-position toggle switch", [("UFC", "ICP·DED 전원"), ("OFF", "OFF")], 4),
    C("MAP", (1,5), "MAP Switch", "2-position toggle switch", [("MAP", "Block 50 비기능"), ("OFF", "OFF")], 5, note="비기능"),
    C("INS", (2,1), "INS Knob", "7-position rotary knob",
      [("OFF", "INS 전원 차단 (전원 인가 후 10초 이상 OFF 유지)"),
       ("STOR_HDG", "MMC 저장 정렬 데이터로 Stored Heading 정렬 — 신속 (전원 차단 후 이동 없었을 때)"),
       ("NORM", "수동 입력 위치로 Normal Gyrocompass 정렬 — 시간 더 소요, 이동 후에도 신뢰"),
       ("NAV", "정렬 완료 후 정상 항법"),
       ("CAL", "기능 없음"),
       ("IN_FLT_ALIGN", "공중 정렬 — 일정 방위·안정 자세 유지 필요. 초기에는 Attitude 모드"),
       ("ATT", "자세 모드 — 피치/롤/방위만, 항법 정보 없음 (TACAN 제외)")], 8,
      note="정렬 중 항공기 이동·재배치·외부장비 재구성·무장 재장착 금지"),
    C("GPS", (2,2), "GPS Switch", "2-position toggle switch",
      [("GPS", "GPS 수신기 전원 (하늘 시야 필요. 임무 날짜 1994-03-28 이후, USA 연합 아니면 정밀도 저하 — SATNAV 옵션으로 해제 가능)"), ("OFF", "OFF")], 6),
    C("DL", (2,3), "DL Switch", "2-position toggle switch", [("DL", "SMDL 보안 모뎀 데이터링크 전원"), ("OFF", "OFF")], 7, note=NI),
    C("MIDS_LVT", (2,5), "MIDS LVT Knob", "3-position rotary knob",
      [("ZERO", "MIDS LVT 내부 메모리 민감 데이터 제로화"), ("OFF", "MIDS LVT 전원 차단"), ("ON", "MIDS LVT 전원 — Link 16 (TNDL)")], 9),
]),

P("RCONSMISC", "R CONSOLE MISC", "RIGHT CONSOLE MISC (NUCLEAR CONSENT / SEAT ADJ / ZEROIZE / VOICE MESSAGE / UTILITY LIGHT / DTU)", "Right Console", "75", 2, 3, [
    C("NUCLEAR_CONSENT", (1,1), "NUCLEAR CONSENT Switch", "3-position guarded toggle switch",
      [("ARM", "핵무장 동의"), ("OFF", "OFF"), ("REL_ARM", "투하 동의")], None, note=NI + " — p.75 개요도에만 표기, 각인 기준"),
    C("SEAT_ADJ", (1,2), "SEAT ADJ Switch", "3-position momentary toggle switch",
      [("UP", "좌석 상승"), ("OFF", "정지"), ("DN", "좌석 하강")], None, note="p.75 개요도에만 표기"),
    C("ZEROIZE", (1,3), "ZEROIZE Switch", "2-position guarded toggle switch",
      [("ZEROIZE", "암호/민감 데이터 제로화"), ("OFF", "정상")], None, note="p.75 개요도에만 표기, 각인 기준"),
    C("VOICE_MESSAGE", (2,1), "VOICE MESSAGE Switch", "2-position toggle switch",
      [("VOICE_MESSAGE", "VMS 음성 경고 활성"), ("INHIBIT", "VMS 음성 경고 억제")], None, note="p.75 개요도에만 표기, 각인 기준"),
    C("UTILITY_LIGHT", (2,2), "Utility Light", "Hand-held light (switch)",
      [("OFF", "OFF"), ("ON", "ON")], None, note="p.75 개요도에만 표기"),
    IND("DTU", (2,3), "DTU Receptacle", "데이터 전송 카트리지 삽입구", None, note="p.75 개요도에만 표기"),
], note="p.75 Right Console 개요도에 표기되었으나 본문 설명이 없는 항목 모음 — 상세는 해당 장 확인 필요"),
]
